// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Simulator")>]
[<assembly: AssemblyProductAttribute("DECAD")>]
[<assembly: AssemblyDescriptionAttribute("Schematic editor and Simulator")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
[<assembly: InternalsVisibleToAttribute("Simulator.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Simulator"
    let [<Literal>] AssemblyProduct = "DECAD"
    let [<Literal>] AssemblyDescription = "Schematic editor and Simulator"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyConfiguration = "Debug"
    let [<Literal>] InternalsVisibleTo = "Simulator.Tests"
