// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("WidthInferer")>]
[<assembly: AssemblyProductAttribute("issie")>]
[<assembly: AssemblyDescriptionAttribute("Schematic editor and Simulator")>]
[<assembly: AssemblyVersionAttribute("0.5.0")>]
[<assembly: AssemblyFileVersionAttribute("0.5.0")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
[<assembly: InternalsVisibleToAttribute("WidthInferer.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "WidthInferer"
    let [<Literal>] AssemblyProduct = "issie"
    let [<Literal>] AssemblyDescription = "Schematic editor and Simulator"
    let [<Literal>] AssemblyVersion = "0.5.0"
    let [<Literal>] AssemblyFileVersion = "0.5.0"
    let [<Literal>] AssemblyConfiguration = "Debug"
    let [<Literal>] InternalsVisibleTo = "WidthInferer.Tests"
