# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ISSIE
email: t.clarke@imperial.ac.uk
description: >- # this means to ignore newlines until "baseurl:"
  Discover, Learn & Create with the ISSIE circuit schematic editor!
baseurl: "/issie" # the subpath of your site, e.g. /blog
url: "https://tomcl.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: tomcl
github_username:  tomcl
show_downloads: true

# Build settings
paginate: 3
paginate_path: "/blog/page:num/"
theme: jekyll-theme-architect
plugins:
  - jekyll-feed
  - jekyll-paginate

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

github:
  windows: https://github.com/tomcl/issie/releases/download/v2.4.5/issie-2.4.5-win.zip
  macos: https://github.com/tomcl/issie/releases/download/v2.4.5/issie-2.4.5.dmg
  blog: https://github.com/tomcl/issie/wiki/Issie-Blog
  
markdown: kramdown

kramdown:
  parse_block_html: true

