// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Main")>]
[<assembly: AssemblyProductAttribute("issie")>]
[<assembly: AssemblyDescriptionAttribute("Schematic editor and Simulator")>]
[<assembly: AssemblyVersionAttribute("0.5.0")>]
[<assembly: AssemblyFileVersionAttribute("0.5.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
[<assembly: InternalsVisibleToAttribute("Main.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Main"
    let [<Literal>] AssemblyProduct = "issie"
    let [<Literal>] AssemblyDescription = "Schematic editor and Simulator"
    let [<Literal>] AssemblyVersion = "0.5.0"
    let [<Literal>] AssemblyFileVersion = "0.5.0"
    let [<Literal>] AssemblyConfiguration = "Release"
    let [<Literal>] InternalsVisibleTo = "Main.Tests"
