// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection
open System.Runtime.CompilerServices

[<assembly: AssemblyTitleAttribute("Main")>]
[<assembly: AssemblyProductAttribute("ISSIE")>]
[<assembly: AssemblyDescriptionAttribute("Schematic editor and Simulator")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
[<assembly: AssemblyConfigurationAttribute("Debug")>]
[<assembly: InternalsVisibleToAttribute("Main.Tests")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Main"
    let [<Literal>] AssemblyProduct = "ISSIE"
    let [<Literal>] AssemblyDescription = "Schematic editor and Simulator"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
    let [<Literal>] AssemblyConfiguration = "Debug"
    let [<Literal>] InternalsVisibleTo = "Main.Tests"
