(*
  This module coordinates the draw block user interface managing component selection, moving, auto-scrolling etc
*)

module Sheet
open CommonTypes
open Fable.React
open Browser
open Elmish
open DrawHelpers
open DrawModelType
// open DrawModelType.SymbolT
open DrawModelType.SheetT
open Optics
open Operators

// HLP 23 AUTHOR: BRYAN TAN
open SymbolHelpers
open BusWireRoutingHelpers




/// return X=CanvasDiv.scrollLeft, Y= canvasDiv.scrollTop
let getScrollProps() =
    document.getElementById "Canvas"
    |> (fun el -> if el = null then None else Some {X=el.scrollLeft; Y=el.scrollTop})

let putScrollProps (props: XYPos) =
    document.getElementById "Canvas"
    |> (fun el ->
        if el <> null then
            el.scrollTop <- props.Y;
            el.scrollLeft <- props.X
            Some el
        else
            None)

(*

It is VERY VERY difficult to prevent OnScroll messages generated by programmatic scroll updates
from changing the scroll updates.

Three methods are attempted below. The last one - inhibiting OnScroll messages for the first view function
after any porgrammatic update - appears to work. The other two could probably be deleted.


*)

/// Used to filter OnScroll messages caused by recent scroll updates.
/// These could reset scroll back to some previous value.
let mutable recentProgrammaticScrollPos: XYPos list = []

/// Used to filter out-of-sequence OnScroll messages.
/// These could reset scroll to some previous value.
/// Incremented by program UpdateScroll and OnScroll.
let mutable scrollSequence: int = 0

/// True for the first view function evaluation after scroll has been programmatically updated.
/// In that case OnScroll messages are never sent.
let mutable  viewIsAfterUpdateScroll = false



//-------------------------------------------------------------------------------------------------//
//-----------------------------------Constants used in Sheet---------------------------------------//
//-------------------------------------------------------------------------------------------------//

module Constants =
    /// what is the max length of the UndoList
    let maxUndoListSize = 50
    /// how large is the snapping when moving symbols
    let symbolSnapLimit = 7.
    /// how large is the snapping when moving segments
    let segmentSnapLimit = 7.
    /// Size of each grid square
    let gridSize = 30.0
    /// total size of canvas (determines how far you can zoom out)
    let defaultCanvasSize = 3500.
    /// increase to make it easier to select wire segments
    let wireBoundingBoxSize = 2.
    /// max zoom beyond which it is not worth going
    let maxMagnification = 2.
    /// how much is it possible to zoom out? this is related to the actual canvas size
    let minMagnification = 0.1
    /// factor by which zoom is increased or decreased
    let zoomIncrement = 1.2
    /// aspect ratio required before align or distribute can be done
    let boxAspectRatio = 2. 
    /// id of the Sheet menu's dropdown, which when pinned covers the left of the canvas.
    /// TopMenuView.fileTab puts this on the element; nothing else knows the two are the same.
    let sheetMenuId = "SheetMenuDropdown"
    /// How lopsided the canvas beside a pinned Sheet menu may be before a sheet is sized to the
    /// whole canvas instead. Dodging a menu that leaves a tall slot costs more magnification than
    /// seeing the sheet whole under it, and the menu is see-through-able by unpinning.
    let maxFitAspectRatio = 3.
    /// geometry parameters for sizing circuits
    let boxParameters = {|
            BoxOfEmptyCircuit = ({X=100.;Y=100.}:XYPos)
            BoxMin = 30.; // minimum white edge in pixels after ctrlW
            BoxMarginFraction = 0.1;  // minimum white edge as fraction of screen after ctrlW
            CanvasBorder = 0.5 // minimum scrollable white space border as fraction of circuit size after ctrlW
            CanvasExtensionFraction = 0.1 // fraction of screen size used to extend canvas by when going off edge
        |}
    

//---------------------------------------Derived constants----------------------------------------//


//-------------------------------------------------------------------------------------------------//
// ------------------ Helper Functions that need to be before the Model type extensions ---------- //
//-------------------------------------------------------------------------------------------------//

let centreOfCanvas (model:Model) =
    let dim = model.CanvasSize / 2.
    {X=dim; Y=dim}

/// Creates a command to Symbol
let symbolCmd (msg: SymbolT.Msg) = Cmd.ofMsg (ModelType.Msg.Sheet (Wire (BusWireT.Symbol msg)))

/// Creates a command to BusWire
let wireCmd (msg: BusWireT.Msg) = Cmd.ofMsg (ModelType.Msg.Sheet (Wire msg))

let sheetCmd (msg: SheetT.Msg) = Cmd.ofMsg (ModelType.Msg.Sheet msg)





//-------------------------------------------------------------------------------------------------//
// ------------------------------------- Issie Interfacing functions ----------------------------- //
//-------------------------------------------------------------------------------------------------//

module SheetInterface =
    type Model with

        member this.ChangeComponent (dispatch: Dispatch<Msg>) (symModel: SymbolT.Model) (compId: ComponentId) (compType:ComponentType) =
            let delPorts = SymbolPortHelpers.findDeletedPorts this.Wire.Symbol compId (this.GetComponentById compId) compType
            Log.dbg Log.Symbol $"changing component to {compType}, deleting {delPorts.Length} ports"
            let wireModel, wireMsgOpt =
                BusWireUpdateHelpers.deleteWiresWithPort delPorts {this.Wire with Symbol = symModel}
                |> (fun model -> BusWireSeparate.routeAndSeparateSymbolWires model compId)
                |> BusWireUpdate.calculateBusWidths
            dispatch <| SetWireModel wireModel
            wireMsgOpt
            |> Option.iter (fun msg -> dispatch <| Wire msg)

        /// Given a compType, return a label
        member this.GenerateLabel (compType: ComponentType) : string =
            SymbolUpdate.generateLabel this.Wire.Symbol compType

        /// Given a compId, return the corresponding component
        member this.GetComponentById (compId: ComponentId) =
            SymbolUpdate.extractComponent this.Wire.Symbol compId

        /// Change the label of Component specified by compId to lbl
        member this.ChangeLabel (dispatch: Dispatch<Msg>) (compId: ComponentId) (lbl: string) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeLabel (compId, lbl) ) ) )

        /// Run Bus Width Inference check
        member this.DoBusWidthInference dispatch =
            dispatch <| (Wire (BusWireT.BusWidths))

        /// Given a compId and a width, update the width of the Component specified by compId
        member this.ChangeWidth (dispatch: Dispatch<Msg>) (compId: ComponentId) (width: int) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeNumberOfBits (compId, width) ) ) )
            this.DoBusWidthInference dispatch

        /// Given a compId and a width, update the width of the Component specified by compId
        member this.ChangeScale (dispatch: Dispatch<Msg>) (compId: ComponentId) (newScale: float) (whichScale:ScaleAdjustment) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeScale (compId, newScale, whichScale) ) ) )
            dispatch <| (Wire (BusWireT.UpdateSymbolWires compId))

        member this.ChangeAdderComp (dispatch: Dispatch<Msg>) (compId: ComponentId) (newComp:ComponentType) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeAdderComponent (compId,(this.GetComponentById compId), newComp) ) ) )
            let delPorts = SymbolPortHelpers.findDeletedPorts this.Wire.Symbol compId (this.GetComponentById compId) newComp
            dispatch <| (Wire (BusWireT.DeleteWiresWithPort delPorts))
            dispatch <| (Wire (BusWireT.UpdateSymbolWires compId))
            //this.DoBusWidthInference dispatch
        
        member this.ChangeCounterComp (dispatch: Dispatch<Msg>) (compId: ComponentId) (newComp:ComponentType) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeCounterComponent (compId,(this.GetComponentById compId), newComp) ) ) )
            let delPorts = SymbolPortHelpers.findDeletedPorts this.Wire.Symbol compId (this.GetComponentById compId) newComp
            dispatch <| (Wire (BusWireT.DeleteWiresWithPort delPorts))
            dispatch <| (Wire (BusWireT.UpdateSymbolWires compId))
        
        /// Given a compId, update the ReversedInputs property of the Component specified by compId
        member this.ChangeReversedInputs (dispatch: Dispatch<Msg>) (compId: ComponentId) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeReversedInputs (compId) ) ) )
            dispatch <| (Wire (BusWireT.UpdateSymbolWires compId))
            this.DoBusWidthInference dispatch

        /// Given a compId and the number in inputs, set the number of inputs for a gate
        member this.ChangeGate (dispatch: Dispatch<Msg>) (compId: ComponentId) (gateType: GateComponentType) (n: int) =
            let symModel = SymbolUpdate.ChangeGate (compId, gateType, n) this.Wire.Symbol
            this.ChangeComponent dispatch symModel compId (GateN (gateType, n))

        /// Given a compId, number of inputs
        member this.ChangeMergeN (dispatch: Dispatch<Msg>) (compId: ComponentId) (numInputs: int) =
            let symModel = SymbolUpdate.ChangeMergeN (compId,numInputs) this.Wire.Symbol
            this.ChangeComponent dispatch symModel compId (MergeN numInputs)


        /// Given comId, number of inputs, widths and LSBs
        member this.ChangeSplitN (dispatch: Dispatch<Msg>) (compId: ComponentId) (numInputs: int) (widths : int list) (lsbs: int list) =
            let symModel = SymbolUpdate.ChangeSplitN (compId,numInputs,widths,lsbs) this.Wire.Symbol
            this.ChangeComponent dispatch symModel compId  (SplitN (numInputs, widths, lsbs))


        /// Given a compId and a LSB, update the LSB of the Component specified by compId
        member this.ChangeLSB (dispatch: Dispatch<Msg>) (compId: ComponentId) (lsb: bigint) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeLsb (compId, lsb) ) ) )

        member this.ChangeInputValue (dispatch: Dispatch<Msg>) (compId: ComponentId) (newVal: bigint) =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.ChangeInputValue (compId, newVal))))

        /// Return Some string if Sheet / BusWire / Symbol has a notification, if there is none then return None
        member this.GetNotifications =
            // Currently only BusWire has notifications
            this.Wire.Notifications

        /// Get the current canvas state in the form of (Component list * Connection list)
        member this.GetCanvasState () =
            let compList = SymbolUpdate.extractComponents this.Wire.Symbol
            let connList = BusWire.extractConnections this.Wire

            compList, connList

        /// Clears the Undo and Redo stack of Sheet
        member this.FlushCommandStack dispatch =
            dispatch <| FlushCommandStack

        /// Clears the canvas, removes all components and connections
        member this.ClearCanvas dispatch =
            dispatch <| ResetModel
            dispatch <| Wire BusWireT.ResetModel
            dispatch <| Wire (BusWireT.Symbol (SymbolT.ResetModel ) ) 

        /// Returns a list of selected components
        member this.GetSelectedComponents =
            this.SelectedComponents
            |> List.collect ( fun compId ->
                if Map.containsKey compId this.Wire.Symbol.Symbols then
                    [SymbolUpdate.extractComponent this.Wire.Symbol compId]
                else
                    [])
        
        /// Returns a list of selected connections
        member this.GetSelectedConnections =
            this.SelectedWires
            |> List.collect (fun connId ->
                if Map.containsKey connId this.Wire.Wires then
                    [BusWire.extractConnection this.Wire connId]
                else 
                    [])
        
        /// Returns a list of selected components and connections in the form of (Component list * Connection list)
        member this.GetSelectedCanvasState =
            this.GetSelectedComponents, this.GetSelectedConnections

        /// Given a list of connIds, select those connections
        member this.SelectConnections dispatch on connIds =
            dispatch <| UpdateSelectedWires (connIds, on)
        /// Update the memory of component
        member this.WriteMemoryType dispatch compId mem =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.WriteMemoryType (compId,mem))))
                /// Update the memory of component
        member this.UpdateMemory dispatch compId mem =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.UpdateMemory (compId,mem))))

        /// Update the memory of component specified by connId at location addr with data value
        member this.WriteMemoryLine dispatch connId addr value =
            dispatch <| (Wire (BusWireT.Symbol (SymbolT.WriteMemoryLine (connId, addr, value))))

//-------------------------------------------------------------------------------------------------//
// ------------------------------------------- Helper Functions ------------------------------------------- //
//-------------------------------------------------------------------------------------------------//


  

//Calculates the symmetric difference of two lists, returning a list of the given type
let symDiff lst1 lst2 =
    let a = Set.ofList lst1
    let b = Set.ofList lst2
    (a - b) + (b - a)
    |> Set.toList

/// return screen edge coords if possible
let getScreenEdgeCoords (model:Model) =
    let canvas = document.getElementById "Canvas"
    if canvas = null then None
    else
        let wholeApp = document.getElementById "WholeApp"
        let rightSelection = document.getElementById "RightSelection"
        let topMenu = document.getElementById "TopMenu"
        let scrollDeviation = model.ScreenScrollPos - {X=canvas.scrollLeft;Y=canvas.scrollTop}
        let leftScreenEdge = canvas.scrollLeft
        let rightScreenEdge = leftScreenEdge + wholeApp.clientWidth - rightSelection.offsetWidth
        let topScreenEdge = canvas.scrollTop
        let bottomScreenEdge = topScreenEdge + rightSelection.offsetHeight - topMenu.clientHeight
        Some {|Left=leftScreenEdge;Right=rightScreenEdge;Top=topScreenEdge;Bottom=bottomScreenEdge|}

let centreOfScreen model : XYPos option =
    getScreenEdgeCoords model
    |> Option.map ( fun edge -> 
        {
            X = (edge.Left + edge.Right)/(2. * model.Zoom)
            Y = (edge.Top + edge.Bottom)/(2. * model.Zoom)
        })


/// helper used inside Map.tryFind hence the unused parameter
/// returns true if pos is insoie boundingbox
let insideBox (pos: XYPos) boundingBox =
    let {BoundingBox.TopLeft={X = xBox; Y=yBox}; H=hBox; W=wBox} = boundingBox
    pos.X >= xBox && pos.X <= xBox + wBox && pos.Y >= yBox && pos.Y <= yBox + hBox  

/// Checks if pos is inside any of the bounding boxes of the components in boundingBoxes
let inline insideBoxMap 
        (boundingBoxes: Map<CommonTypes.ComponentId, BoundingBox>) 
        (pos: XYPos) 
            : CommonTypes.ComponentId Option =
    boundingBoxes
    |> Map.tryFindKey (fun k box -> insideBox pos box)// If there are multiple components overlapping (should not happen), return first one found

/// returns the symbol if pos is inside any symbol's LabelBoundingBox
let inline tryInsideLabelBox  (model: Model) (pos: XYPos) =
    Optic.get symbols_ model
    |> Map.tryPick (fun (sId:ComponentId) (sym:SymbolT.Symbol) ->
        if insideBox pos sym.LabelBoundingBox then Some sym else None)

/// HLP23 AUTHOR: BRYAN TAN
/// if pos is inside any one of the custom symbol's corners, return the diagonally opposite corner (its position is fixed during resizing), and the index of the corner being held
let inline tryInsideSymCorner (model: Model) (pos: XYPos) =
    let radius = 5.0
    let margin = 2.5
    
    let insideCircle (pos: XYPos) (circleLocation: XYPos) radius margin: bool =
        let distance = ((pos.X - circleLocation.X) ** 2.0 + (pos.Y - circleLocation.Y) ** 2.0) ** 0.5
        distance <= radius + margin

    let tryGetOppositeCorners corners= 
        match corners with
        | [||] -> None // should never match
        | _ -> 
            Array.tryFindIndex (fun c -> insideCircle pos c radius margin) corners
            |> function
                | Some idx -> Some (corners[(idx + 2) % 4], idx)
                | None -> None

    Optic.get symbols_ model
    |> Map.tryPick (fun (sId:ComponentId) (sym:SymbolT.Symbol) ->   
        match sym.Component.Type with
        | CommonTypes.Custom _ -> 
            getCustomSymCorners sym
            |> (translatePoints sym.Pos)
            |> tryGetOppositeCorners
            |> function
                | Some (fp, p) -> Some (sym, fp, p)
                | _ -> None
        | _ -> None
    )

/// return a BB equivalent to input but with (X,Y) = LH Top coord, (X+W,Y+H) = RH bottom coord
/// note that LH Top is lower end of the two screen coordinates
let standardiseBox (box:BoundingBox) =
    let x = min box.TopLeft.X (box.TopLeft.X+box.W)
    let y = min box.TopLeft.Y (box.TopLeft.Y+box.H)
    let w = abs box.W
    let h = abs box.H
    { TopLeft = {X=x; Y=y} ; W=w;H=h}


let transformScreenToPos (screenPos:XYPos) (scrollPos:XYPos) mag =
    {X=(screenPos.X + scrollPos.X)/mag;
     Y=(screenPos.Y + scrollPos.Y)/mag}


/// calculates the smallest bounding box that contains two BBs, in form with W,H > 0
let boxUnion (box:BoundingBox) (box':BoundingBox) =
    let maxX = max (box.TopLeft.X+box.W) (box'.TopLeft.X + box'.W)
    let maxY = max (box.TopLeft.Y + box.H) (box'.TopLeft.Y + box'.H)
    let minX = min box.TopLeft.X box'.TopLeft.X
    let minY = min box.TopLeft.Y box'.TopLeft.Y
    {
        TopLeft = {X = minX; Y = minY}
        W = maxX - minX
        H = maxY - minY
    }

/// Returns the smallest BB containing box and point.
/// Could be made more efficient
let boxPointUnion (box: BoundingBox) (point: XYPos) =
    let pBox = {TopLeft=point; W=0.;H=0.}
    boxUnion box pBox
    
let symbolToBB (centresOnly: bool) (symbol:SymbolT.Symbol) =
    let co = symbol.Component
    let h,w = Symbol.getRotatedHAndW symbol
    if centresOnly then
        {TopLeft = symbol.Pos + {X=w/2.; Y=h/2.}; W=0.;H=0.}
    else
        {TopLeft = symbol.Pos; W=w; H=h}

let symbolToCentre (symbol:SymbolT.Symbol) =
    let h,w = Symbol.getRotatedHAndW symbol
    {TopLeft = symbol.Pos + {X=w/2.; Y = h / 2.}; W=0.1; H=0.1}

/// Returns the smallest BB that contains all segments
/// of wire.
let wireToBB (wire:BusWireT.Wire) =
    let initBox = {TopLeft=wire.StartPos;W=0.;H=0.}
    (initBox,wire)
    ||> BlockHelpers.foldOverNonZeroSegs (fun _ ePos box _ -> 
        boxPointUnion box ePos)


let symbolBBUnion (centresOnly: bool) (symbols: SymbolT.Symbol list) :BoundingBox option =
    match symbols with
    | [] -> None
    | sym :: rest ->
        (symbolToBB centresOnly sym, rest)
        ||> List.fold (fun (box:BoundingBox) sym ->
                if centresOnly then
                    boxUnion (symbolToBB centresOnly sym) box
                else
                    boxUnion box (boxUnion (symbolToBB centresOnly sym) (sym.LabelBoundingBox)))
        |> Some
    


/// Returns the smallest BB that contains all symbols, labels, and wire segments.
/// For empty circuit a BB is returned in middle of viewable screen.
let symbolWireBBUnion (model:Model) =
    let symbols =
        model.Wire.Symbol.Symbols
        |> Helpers.mapValues
        |> Array.toList
    let symbolBB =
        symbols
        |> symbolBBUnion false
    let labelsBB =
        symbols
        |> List.map (fun sym -> (Symbol.calcLabelBoundingBox sym).LabelBoundingBox)
    let labelBB =
        match labelsBB with
        | [] -> None
        | _ -> Some <| List.reduce boxUnion labelsBB
    let wireBB =
        let wiresBBA = 
            model.Wire.Wires
            |> Helpers.mapValues
            |> Array.map wireToBB
        match wiresBBA with
        | [||] -> None
        |  _ ->
            wiresBBA
            |> Array.reduce boxUnion
            |> Some
    [symbolBB;labelBB;wireBB]
    |> List.collect (function | Some bb -> [bb] | _ -> [])
    |> function | [] -> {TopLeft=Option.defaultValue XYPos.zero (centreOfScreen model); W=0.;H=0.}
                | [bb] -> bb
                | bbL -> List.reduce boxUnion bbL

let moveCircuit moveDelta (model: Model) =
    model
    |> Optic.map symbol_ (BlockHelpers.moveSymbols moveDelta)
    |> Optic.map wire_ (BlockHelpers.moveWires moveDelta)
    |> Optic.map wire_ (BusWireSeparate.updateWireSegmentJumpsAndSeparations [])

/// Width of the canvas's left edge the Sheet menu is over, and 0 when the menu is closed - which
/// is display:none, and so has no width. Read from the DOM, as the other screen geometry here is:
/// the draw block has no view of the top menu's model.
let openSheetMenuWidth () =
    let menu = document.getElementById Constants.sheetMenuId
    if menu = null then 0. else menu.offsetWidth

/// Whether the Sheet menu is pinned, which is when it is there to be worked beside rather than
/// dismissed, and so when a fit goes round it rather than under it.
let sheetMenuIsPinned () =
    let menu = document.getElementById Constants.sheetMenuId
    menu <> null && menu.getAttribute "data-pinned" = "true"

/// How much of the left of a `width` by `height` canvas a fit should leave to a menu `menuWidth`
/// wide: all of it, unless what is left over is a slot more than Constants.maxFitAspectRatio times
/// as tall as it is wide (or as wide as tall), where going round the menu would shrink the circuit
/// further than the menu ever hides it.
let fitInsetFor (menuWidth: float) (width: float) (height: float) =
    let clear = width - menuWidth
    if menuWidth > 0. && clear > 0. && height > 0.
       && max (clear/height) (height/clear) <= Constants.maxFitAspectRatio
    then menuWidth
    else 0.

/// Whether pinning the Sheet menu would shrink the sheet into the canvas beside it rather than
/// leave it fitted to the whole canvas. Asked by the pin itself, which cannot go through
/// sheetMenuIsPinned: it is in the middle of changing the attribute that reads.
let pinningSheetMenuWouldRefit (model: Model) =
    getScreenEdgeCoords model
    |> Option.map (fun edge ->
        fitInsetFor (openSheetMenuWidth ()) (edge.Right - edge.Left) (edge.Bottom - edge.Top) > 0.)
    |> Option.defaultValue false

/// What a fit of `box` has to work with: the part of the window it may use, how far in from the
/// left that starts, and the magnification that puts the box in it. Separate from the scroll,
/// because the canvas has to be sized for the scroll before the scroll can be asked for - see
/// fitCircuitToWindowParas.
let private screenFitFor model (box: BoundingBox) =
    getScreenEdgeCoords model
    |> Option.map (fun edge ->
        let height = edge.Bottom - edge.Top
        // A pinned Sheet menu is meant to be worked beside, so the circuit is fitted to the window
        // it leaves clear rather than to the whole window.
        let inset =
            if sheetMenuIsPinned () then
                fitInsetFor (openSheetMenuWidth ()) (edge.Right - edge.Left) height
            else 0.
        let width = edge.Right - edge.Left - inset
        {| Inset = inset
           Width = width
           Height = height
           Mag = min (min (width/box.W) (height/box.H)) Constants.maxMagnification |})

/// get scroll and zoom paras to fit box all on screen centred and occupying as much of screen as possible
let getWindowParasToFitBox model (box: BoundingBox)  =
    screenFitFor model box
    |> Option.map (fun fit ->
        let xMiddle = (box.TopLeft.X + box.W/2.)*fit.Mag
        // the screen edge coords start at the scroll position, so what is subtracted is where in
        // the window the circuit's centre is wanted: past the menu, then half way across the rest
        let xScroll = xMiddle - (fit.Inset + fit.Width/2.)
        let yMiddle = (box.TopLeft.Y + (box.H)/2.)*fit.Mag
        let yScroll = yMiddle - fit.Height/2.
        {|Scroll={X=xScroll; Y=yScroll}; MagToUse=fit.Mag|})

let addBoxMargin (fractionalMargin:float) (absoluteMargin:float) (box: BoundingBox) =
    let boxMargin = 
        (max box.W box.H) * fractionalMargin
        |> max absoluteMargin 
       
    {   TopLeft = box.TopLeft - {X = boxMargin; Y = boxMargin}
        W = box.W + boxMargin*2.
        H = box.H + boxMargin*2.
     }

/// Check that canvas is large enough to have space all round the visible area.
/// If not, then change model by moving circuit on canvas and/or extending canvas.
/// Keep components in same visible position during this process.
/// returns new model with all positions updated if need be.
let ensureCanvasExtendsBeyondScreen model : Model =
    let boxParas = Constants.boxParameters
    let edge = getScreenEdgeCoords model
    let box = 
        symbolWireBBUnion model
        |> addBoxMargin boxParas.CanvasExtensionFraction  boxParas.BoxMin
    let quant = boxParas.CanvasExtensionFraction * min box.H box.W       
    let newSize =
        [box.H;box.W]
        |> List.map (fun x -> x + 4.*quant)
        |> List.max
        |> max model.CanvasSize
    let bottomRight = box.TopLeft + {X=box.W;Y=box.H}
    let size = model.CanvasSize
    let xIsOk = box.TopLeft.X > 0. && bottomRight.X < size
    let yIsOk = box.TopLeft.Y > 0. &&  bottomRight.Y < size
    if xIsOk && yIsOk then
        model
    else
        let circuitMove = 
            box
            |> (fun bb -> 
                let centre = bb.Centre()
                {
                    X = if xIsOk then 0. else newSize/2.- centre.X
                    Y = if yIsOk then 0. else newSize/2. - centre.Y
                })
        scrollSequence <- scrollSequence + 1
        let newScrollPos = model.ScreenScrollPos + circuitMove*model.Zoom 
        putScrollProps newScrollPos |> ignore
        let posDelta :(XYPos -> XYPos) = ((+) circuitMove)
        let posScreenDelta :(XYPos -> XYPos) = ((+) (circuitMove*model.Zoom))
        model 
        |> moveCircuit circuitMove
        |> Optic.map screenScrollPos_ posDelta 
        |> Optic.set canvasSize_ newSize
        |> Optic.map screenScrollPos_ posScreenDelta
        |> Optic.map lastMousePos_ posDelta
        |> Optic.map lastMousePosForSnap_ posDelta
        |> Optic.map (scrollingLastMousePos_ >-> pos_) posDelta
        
           







/// How big the canvas must be for the circuit to sit in the middle of it with room around it, how
/// far the circuit has to move to get there, and where its bounding box lands once it has.
/// Separate from the move itself, which reroutes every wire, so that a question about where a fit
/// would put things can be asked without paying for one.
let private centredCircuitBox (model: Model) =
    let boxParas = Constants.boxParameters
    let sBox =
        symbolWireBBUnion model
        |> addBoxMargin boxParas.BoxMarginFraction boxParas.BoxMin
    /// The canvas must also be long enough to scroll to where the fit wants the circuit, because
    /// scrolling stops at the canvas edge. Centred on the canvas, the circuit has
    /// `CanvasSize/2 * mag` of window to its left, and a fit asks for `inset + width/2` of it -
    /// which a canvas sized only around the circuit does not have once a pinned Sheet menu makes
    /// the inset large. The browser then clamps the scroll to 0 and the circuit is left short of
    /// where it should be, sliding back under the menu it was dodging. In draw block units, hence
    /// the division by the magnification.
    let neededToScroll =
        screenFitFor model sBox
        |> Option.map (fun fit ->
            max ((2. * fit.Inset + fit.Width) / fit.Mag) (fit.Height / fit.Mag))
        |> Option.defaultValue 0.
    let newCanvasSize =
        max sBox.W sBox.H
        |> ((*) (1. + 2. * boxParas.CanvasBorder))
        |> max Constants.defaultCanvasSize
        |> max neededToScroll
    let offsetToCentreCircuit =
        {X=newCanvasSize / 2.; Y = newCanvasSize/2.} - sBox.Centre()
    {| CanvasSize = newCanvasSize
       Offset = offsetToCentreCircuit
       Box = {sBox with TopLeft = sBox.TopLeft + offsetToCentreCircuit} |}

/// shift circuit to middle of canvas, resizing canvas to allow enough border if needed.
/// return scroll and zoom paras to display all of circuit in middle of window
let fitCircuitToWindowParas (model:Model) =
    let centred = centredCircuitBox model
    let modelWithMovedCircuit =
        {model with CanvasSize = centred.CanvasSize}
        |> moveCircuit centred.Offset

    match getWindowParasToFitBox model centred.Box with
    | Some paras ->
        {modelWithMovedCircuit with
            Zoom = paras.MagToUse
            ScreenScrollPos = paras.Scroll}, Some paras
    | None -> model, None

/// Whether the sheet is still exactly where a fit would put it, and so has not been scrolled,
/// zoomed or edited since one. Undoing a fit - as unpinning the Sheet menu does - is only ever
/// right for a view the fit itself chose: once the user has moved it, it is theirs.
///
/// A second fit of an already fitted circuit is a no-op, since the circuit is centred on the canvas
/// already and the same box gives the same magnification, so this can ask by computing one.
///
/// Compared against where the canvas is actually scrolled to, not against the model's record of it:
/// a fit that asks to scroll past a canvas edge gets what the browser allows instead, and it is
/// that the user is looking at.
let isAtFittedPosition (model: Model) =
    let canvas = document.getElementById "Canvas"
    match getWindowParasToFitBox model (centredCircuitBox model).Box with
    | _ when canvas = null -> false
    | None -> false
    | Some paras ->
        let asScrolled (wanted: float) (got: float) (limit: float) =
            // a pixel either way is the browser's rounding, not the user moving anything
            abs ((wanted |> max 0. |> min limit) - got) < 2.
        let fitted =
            abs (paras.MagToUse - model.Zoom) < 0.001
            && asScrolled paras.Scroll.X canvas.scrollLeft (canvas.scrollWidth - canvas.clientWidth)
            && asScrolled paras.Scroll.Y canvas.scrollTop (canvas.scrollHeight - canvas.clientHeight)
        Log.dbg Log.Sheet
            $"fitted={fitted}: zoom {model.Zoom} vs {paras.MagToUse}, \
              scroll ({canvas.scrollLeft},{canvas.scrollTop}) vs \
              ({paras.Scroll.X},{paras.Scroll.Y})"
        fitted




let isBBoxAllVisible model (bb: BoundingBox) =
    getScreenEdgeCoords model
    |> Option.map (fun edge ->
        let z = model.Zoom
        let lh,rh,top,bottom = edge.Left/z,edge.Right/z,edge.Top/z,edge.Bottom/z
        let bbs = standardiseBox bb
        lh < bb.TopLeft.Y && 
        top < bb.TopLeft.X && 
        bb.TopLeft.Y+bb.H < bottom && 
        bb.TopLeft.X+bb.W < rh)

/// could be made more efficient, since segments contain redundant info
let getWireBBox (wire: BusWireT.Wire) =
    let updateBoundingBox segStart (segEnd: XYPos) state seg =
        let newTop = min state.TopLeft.Y segEnd.Y
        let newBottom = max (state.TopLeft.Y+state.H) segEnd.Y
        let newRight = max (state.TopLeft.X+state.W) segEnd.X
        let newLeft = min state.TopLeft.X segEnd.X
        {TopLeft={X=newTop; Y=newLeft}; W=newRight-newLeft; H=newBottom-newTop }
    BlockHelpers.foldOverSegs updateBoundingBox {TopLeft = wire.StartPos; W=0; H=0;} wire
    

let isAllVisible (model: Model)(conns: ConnectionId list) (comps: ComponentId list) =
    let wVisible =
        conns
        |> List.map (fun cid -> Map.tryFind cid model.Wire.Wires |> Option.toList)
        |> List.concat
        |> List.map (fun wire -> getWireBBox wire)
        |> List.map (isBBoxAllVisible model >> Option.defaultValue true)
        |> List.fold (&&) true
    let cVisible =
        comps
        |> List.collect (fun comp ->
            if Map.containsKey comp model.Wire.Symbol.Symbols then 
                [Symbol.getBoundingBox model.Wire.Symbol comp]
            else
                [])
        |> List.map (fun bBox -> Option.defaultValue false (isBBoxAllVisible model bBox))
        |> List.fold (&&) true
    wVisible && cVisible


    
/// Finds all components that touch a bounding box (which is usually the drag-to-select box)
let findIntersectingComponents (model: Model) (box1: BoundingBox) =
    model.BoundingBoxes
    |> Map.filter (fun id boundingBox -> (Map.find id (model.Wire.Symbol.Symbols)).Annotation = None && boxesIntersect boundingBox box1)
    |> Map.toList
    |> List.map fst

let posAdd (pos : XYPos) (a : float, b : float) : XYPos =
    {X = pos.X + a; Y = pos.Y + b}

/// Finds all components (that are stored in the Sheet model) near pos
let findNearbyComponentsOld (model: Model) (pos: XYPos) (range: float)  =
    // Larger Increments -> More Efficient. But can miss small components then.
    List.allPairs [-range .. 10.0 .. range] [-range .. 10.0 .. range] 
    |> List.map ((fun x -> posAdd pos x) >> insideBoxMap model.BoundingBoxes)
    |> List.collect ((function | Some x -> [x] | _ -> []))

/// Finds all components (that are stored in the Sheet model) near pos
/// Optimised a little for space
let findNearbyComponents (model: Model) (pos: XYPos) (range: float)  =
    /// for space efficiency construct list mutably.
    /// this happens every move
    let mutable closeComps = []
    for x in 10.0 - range .. 10.0 .. 10.0 + range do
        for y in 10.0 - range .. 10.0 .. 10.0 + range do
            {X=x + pos.X; Y=y + pos.Y}
            |> insideBoxMap model.BoundingBoxes
            |> (function | Some cId -> closeComps <- cId :: closeComps | None -> ())
    closeComps
            


/// Checks if pos is inside any of the ports in portList
let mouseOnPort portList (pos: XYPos) (margin: float) =
    let radius = 5.0

    // TODO: Abstract this out? Also used to detect corners
    let insidePortCircle (pos: XYPos) (portLocation: XYPos): bool =
        let distance = ((pos.X - portLocation.X) ** 2.0 + (pos.Y - portLocation.Y) ** 2.0) ** 0.5
        distance <= radius + margin

    // + 2.5 margin to make it a bit easier to click on, maybe it's due to the stroke width?
    match List.tryFind (fun (_, portLocation) -> insidePortCircle pos portLocation) portList with 
    | Some (portId, portLocation) -> Some (portId, portLocation)
    | None -> None

/// Returns the ports of all model.NearbyComponents
let findNearbyPorts (model: Model) =
    let inputPortsMap, outputPortsMap = Symbol.getPortLocations model.Wire.Symbol model.NearbyComponents

    (inputPortsMap, outputPortsMap) ||> (fun x y -> (Map.toList x), (Map.toList y))

/// Returns what is located at pos.
/// Priority Order: InputPort -> OutputPort -> Label -> Wire -> Component -> Canvas
let mouseOn (model: Model) (pos: XYPos) : MouseOn =

    let inputPorts, outputPorts = findNearbyPorts model
    match mouseOnPort inputPorts pos 2.5 with
    | Some (portId, portLoc) -> InputPort (portId, portLoc)
    | None ->
        match mouseOnPort outputPorts pos 2.5 with
        | Some (portId, portLoc) -> OutputPort (portId, portLoc)
        | None ->
            match tryInsideSymCorner model pos with
            | Some (sym, fixedCorner, mCorner) -> ComponentCorner (sym.Id, fixedCorner, mCorner)
            | None ->
                match tryInsideLabelBox model pos with
                | Some sym -> Label sym.Id
                | None ->
                    match BusWireUpdate.getClickedWire model.Wire pos (Constants.wireBoundingBoxSize/model.Zoom) with
                    | Some connId -> Connection connId
                    | None ->
                        match insideBoxMap model.BoundingBoxes pos with
                        | Some compId -> Component compId
                        | None -> Canvas


let notIntersectingComponents (model: Model) (box1: BoundingBox) (inputId: CommonTypes.ComponentId) =
   model.BoundingBoxes
   |> Map.filter (fun sId boundingBox -> boxesIntersect boundingBox box1 && inputId <> sId)
   |> Map.isEmpty

let notIntersectingSelectedComponents (model: Model) (box1: BoundingBox) (inputId: CommonTypes.ComponentId) =
   model.BoundingBoxes |> Map.filter (fun sId _ -> List.contains sId model.SelectedComponents)
   |> Map.filter (fun sId boundingBox -> boxesIntersect boundingBox box1 && inputId <> sId)
   |> Map.isEmpty


